"""add product color col

Revision ID: 36fd6ed88a68
Revises: 39f50d050713
Create Date: 2023-03-27 08:39:40.318466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36fd6ed88a68"
down_revision = "39f50d050713"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variant",
        sa.Column("color", sa.String(length=15), nullable=True),
    )
    op.execute("UPDATE product_variant SET color = '#000000'")
    op.alter_column("product_variant", "color", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variant", "color")
    # ### end Alembic commands ###
